# Generated by Django 5.0.6 on 2026-06-15 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competizione',
            fields=[
                ('id_concorso', models.AutoField(primary_key=True, serialize=False)),
                ('classifica', models.IntegerField(blank=True, null=True)),
                ('numero_giudici', models.IntegerField()),
            ],
            options={
                'db_table': 'Competizione',
            },
        ),
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('livello', models.CharField(blank=True, choices=[('Base', 'Base'), ('Intermedio', 'Intermedio'), ('Avanzato', 'Avanzato'), ('Tutti', 'Tutti')], max_length=50, null=True)),
                ('fascia_eta', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Corsi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('taglia', models.CharField(blank=True, max_length=10, null=True)),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fornitore', models.CharField(blank=True, max_length=150, null=True)),
                ('stato_ordine', models.CharField(choices=[('In magazzino', 'In magazzino'), ('Ordinato', 'Ordinato'), ('Consegnato', 'Consegnato'), ('In uso', 'In uso')], default='In magazzino', max_length=50)),
            ],
            options={
                'db_table': 'Costumi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Maestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('specializzazione', models.CharField(blank=True, max_length=100, null=True)),
                ('compenso_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name_plural': 'Maestre',
                'db_table': 'Maestre',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Saggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('data', models.DateField(blank=True, null=True)),
                ('luogo', models.CharField(blank=True, max_length=200, null=True)),
                ('ora_inizio', models.TimeField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('In preparazione', 'In preparazione'), ('Programmato', 'Programmato'), ('Completato', 'Completato'), ('Rinviato', 'Rinviato')], default='In preparazione', max_length=50)),
                ('numero_atti', models.IntegerField(default=1)),
                ('durata_totale', models.IntegerField(default=0, help_text='Durata in minuti')),
            ],
            options={
                'db_table': 'Saggi',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Coreografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('atto', models.IntegerField(default=1)),
                ('ordine_uscita', models.IntegerField(blank=True, null=True)),
                ('musica', models.CharField(blank=True, max_length=200, null=True)),
                ('durata', models.IntegerField(blank=True, help_text='Durata in secondi', null=True)),
                ('id_corso', models.ForeignKey(db_column='id_corso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coreografie', to='academy.corso')),
                ('id_maestra', models.ForeignKey(db_column='id_maestra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coreografie', to='academy.maestra')),
                ('id_saggio', models.ForeignKey(db_column='id_saggio', on_delete=django.db.models.deletion.CASCADE, related_name='coreografie', to='academy.saggio')),
            ],
            options={
                'verbose_name_plural': 'Coreografie',
                'db_table': 'Coreografie',
                'ordering': ['id_saggio', 'atto', 'ordine_uscita'],
            },
        ),
        migrations.CreateModel(
            name='Allieva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_iscrizione', models.DateField(blank=True, null=True)),
                ('certificato_medico', models.DateField(blank=True, help_text='Data di scadenza del certificato medico', null=True)),
                ('id_corso', models.ForeignKey(db_column='id_corso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allieve', to='academy.corso')),
            ],
            options={
                'verbose_name_plural': 'Allieve',
                'db_table': 'Allieve',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AssegnazioneCostume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagato', models.BooleanField(default=False)),
                ('consegnato', models.BooleanField(default=False)),
                ('id_allieva', models.ForeignKey(db_column='id_allieva', on_delete=django.db.models.deletion.CASCADE, related_name='costumi_assegnati', to='academy.allieva')),
                ('id_coreografia', models.ForeignKey(db_column='id_coreografia', on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni_costumi', to='academy.coreografia')),
                ('id_costume', models.ForeignKey(db_column='id_costume', on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni', to='academy.costume')),
            ],
            options={
                'verbose_name_plural': 'Assegnazioni Costumi',
                'db_table': 'Assegnazione_Costumi',
            },
        ),
        migrations.CreateModel(
            name='Lezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno_settimana', models.CharField(choices=[('Lunedì', 'Lunedì'), ('Martedì', 'Martedì'), ('Mercoledì', 'Mercoledì'), ('Giovedì', 'Giovedì'), ('Venerdì', 'Venerdì'), ('Sabato', 'Sabato'), ('Domenica', 'Domenica')], max_length=20)),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('sala', models.CharField(blank=True, max_length=50, null=True)),
                ('id_corso', models.ForeignKey(db_column='id_corso', on_delete=django.db.models.deletion.CASCADE, related_name='lezioni', to='academy.corso')),
                ('id_maestra', models.ForeignKey(db_column='id_maestra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lezioni', to='academy.maestra')),
            ],
            options={
                'db_table': 'Lezioni',
                'ordering': ['giorno_settimana', 'ora_inizio'],
            },
        ),
        migrations.AddField(
            model_name='corso',
            name='id_maestra',
            field=models.ForeignKey(db_column='id_maestra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corsi', to='academy.maestra'),
        ),
        migrations.CreateModel(
            name='PagamentoAllieva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_scadenza', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('Da pagare', 'Da pagare'), ('Pagato', 'Pagato'), ('In ritardo', 'In ritardo')], default='Da pagare', max_length=50)),
                ('descrizione', models.CharField(blank=True, max_length=200, null=True)),
                ('id_allieva', models.ForeignKey(db_column='id_allieva', on_delete=django.db.models.deletion.CASCADE, related_name='pagamenti', to='academy.allieva')),
            ],
            options={
                'db_table': 'Pagamenti_Allieve',
                'ordering': ['-data_scadenza'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoMaestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_scadenza', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('Da pagare', 'Da pagare'), ('Pagato', 'Pagato'), ('In ritardo', 'In ritardo')], default='Da pagare', max_length=50)),
                ('descrizione', models.CharField(blank=True, max_length=200, null=True)),
                ('id_maestra', models.ForeignKey(db_column='id_maestra', on_delete=django.db.models.deletion.CASCADE, related_name='pagamenti', to='academy.maestra')),
            ],
            options={
                'db_table': 'Pagamenti_Maestre',
                'ordering': ['-data_scadenza'],
            },
        ),
        migrations.CreateModel(
            name='IscrizioneCompetizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_allieva', models.ForeignKey(db_column='id_allieva', on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni_competizioni', to='academy.allieva')),
                ('id_concorso', models.ForeignKey(db_column='id_concorso', on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni', to='academy.competizione')),
            ],
            options={
                'db_table': 'Iscrizione_Competizione',
                'unique_together': {('id_allieva', 'id_concorso')},
            },
        ),
    ]
