# Generated by Django 5.0.6 on 2026-06-20 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allieva',
            name='id_corso',
            field=models.ForeignKey(db_column='id_corso', on_delete=django.db.models.deletion.PROTECT, related_name='allieve', to='academy.corso'),
        ),
        migrations.AlterField(
            model_name='coreografia',
            name='id_corso',
            field=models.ForeignKey(db_column='id_corso', on_delete=django.db.models.deletion.PROTECT, related_name='coreografie', to='academy.corso'),
        ),
        migrations.AlterField(
            model_name='coreografia',
            name='id_maestra',
            field=models.ForeignKey(db_column='id_maestra', on_delete=django.db.models.deletion.PROTECT, related_name='coreografie', to='academy.maestra'),
        ),
        migrations.AlterField(
            model_name='corso',
            name='id_maestra',
            field=models.ForeignKey(db_column='id_maestra', on_delete=django.db.models.deletion.PROTECT, related_name='corsi', to='academy.maestra'),
        ),
        migrations.AlterField(
            model_name='lezione',
            name='id_maestra',
            field=models.ForeignKey(db_column='id_maestra', on_delete=django.db.models.deletion.PROTECT, related_name='lezioni', to='academy.maestra'),
        ),
    ]
